# Generated by Django 5.2.5 on 2025-08-22 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A brief title for the task.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of the task.', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Optional due date for the task.', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Indicates whether the task is completed or not.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the task was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the task was last updated.')),
                ('owner', models.ForeignKey(help_text='The user who owns this task.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
